version: "3.8"
services:
  backend:
    build:
      context: ./server
    image: portfolio/server
    ports:
      - 5000:5000
  frontend:
    build:
      context: ./client
    image: portfolio/client
    ports:
      - 3000:80
    depends_on:
      - backend
